#!/usr/bin/env bash

lgtpx-backup() {
# Copyright (c) 2019 George Vezirtzoglou <gv@oceanic.io>

# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:

# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

if [ $# = 0 ]; then
    echo "help goes here";
else
  if [ ! -d /Applications/LogTen Pro.app ] && [ ! -d $HOME/Applications/LogTen Pro.app ]; then
    echo "LogTen Pro X must be installed."
    exit 1
  fi
fi

  local base_dir=$HOME/Library/Containers/com.coradine.LogTenProX/Data/Documents
  local logtenpro_data_dir="LogTenProData"
  local logtenpro_db="LogTenCoreDataStore.sql"
  local dest_dir=${1:-$HOME/Desktop}

  echo "[LogTen Pro X Backup]"
  if test -f $base_dir/$logtenpro_data_dir/$logtenpro_db; then
    echo "[LTPX Backup] Found db at: $base_dir/$logtenpro_data_dir/$logtenpro_db"
    local dest_file=$dest_dir/LogTenPro-Script-Backup-$(date +'%m%d%Y').zip

    if test -f $dest_file; then
      echo "[LTPX Backup] Already backed up today."
    else
      echo "[LTPX Backup] Creating back up at $(dirname "${dest_file}")"
      (cd $base_dir; zip -qrdc  $dest_file $logtenpro_data_dir/*  -x "*.DS_Store";)
      if test -f ${dest_file}; then
        echo "[LTPX Backup] Completed: $(basename ${dest_file})"
      else
        echo "[LTPX Backup] Error!"
      fi
    fi
  else
    echo "[LTPX Backup] No database found at $base_dir"
  fi
}
